create table if not exists notifications
(
    id             bigint auto_increment
        primary key,
    content        varchar(1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                not null,
    created_at     datetime(6)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  null,
    is_read        bit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          null,
    user_id        bigint                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       null,
    expires_at     datetime(6)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  null,
    priority       int                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          null,
    read_at        datetime(6)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  null,
    reference_id   bigint                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       null,
    reference_type varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 null,
    title          varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 not null,
    type           enum ('CALENDAR_EVENT', 'CALENDAR_REMINDER', 'CHAT_MENTION', 'CHAT_MESSAGE', 'CHAT_MESSAGE_REACTION', 'FRIEND_REQUEST', 'FRIEND_REQUEST_ACCEPTED', 'MEETING_CANCELLED', 'MEETING_INVITATION', 'MEETING_REMINDER', 'MEETING_UPDATED', 'POST_COMMENT', 'POST_LIKE', 'POST_MENTION', 'PROJECT_DEADLINE_APPROACHING', 'PROJECT_INVITATION', 'PROJECT_MEMBER_ADDED', 'PROJECT_UPDATED', 'SYSTEM_ANNOUNCEMENT', 'SYSTEM_MAINTENANCE', 'SYSTEM_UPDATE', 'TASK_ASSIGNED', 'TASK_COMMENT', 'TASK_COMPLETED', 'TASK_DUE_SOON', 'TASK_OVERDUE', 'TASK_UPDATED', 'TEAM_INVITATION', 'TEAM_MEMBER_ADDED', 'TEAM_UPDATED') not null,
    is_bookmarked  tinyint(1) default 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         null,
    is_archived    tinyint(1) default 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         null,
    bookmarked_at  timestamp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    null,
    archived_at    timestamp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    null,
    constraint fk_notification_user
        foreign key (user_id) references users (id)
)
    auto_increment = 105;

create index idx_notification_type
    on notifications (type);

create index idx_notification_user_active
    on notifications (user_id, is_archived, created_at);

create index idx_notification_user_created
    on notifications (user_id, created_at);

create index idx_notification_user_read
    on notifications (user_id, is_read);

